### ISSUE TITLE
Error message when modifying assignment

### ISSUE THREAD

**Issue by sdobbs** [JeffersonLab/ccdb#29]
When modifying an assignment using the low-level API, the command completes successfully and the database is modified, but the following error message is thrown:

Traceback (most recent call last):
  File "fix_run_range.py", line 12, in <module>
    provider.update_assignment(assignment)
  File "/group/halld/Software/builds/Linux_CentOS6-x86_64-gcc4.9.2/ccdb/ccdb_1.06.01/python/ccdb/provider.py", line 1252, in update_assignment
    affected_ids=[assignment.**tablename** + assignment(assignment.id)],
TypeError: 'Assignment' object is not callable

**Comment by DraTeots** [comment]
Fixed 02/04/2016...
