### ISSUE TITLE
python interactive interface problem with ccdb 2.0

### ISSUE THREAD

**Issue by markito3** [JeffersonLab/ccdb#67]
Created a database with the CCDB 2 schema as follows:

```
mysqldump -h$host -uccdb_user ccdb > $scratch_dir/ccdb1.sql
mysql -h$host -uccdb_user -e "drop database if exists ccdb2"
mysql -h$host -uccdb_user -e "create database ccdb2"
mysql -h$host -uccdb_user ccdb2 < $scratch_dir/ccdb1.sql
mysql -h$host -uccdb_user ccdb2 < $CCDB_HOME/sql/update_1.00_2.00.sqlite.sql
```
And then ran ccdb v2 on it. The `ccdb ls` command succeeds, `ccdb -i` and then `ls` fails:

```
[marki@lorentz gluex_top]$ which ccdb
/scratch/marki/gluex_install_scratch/172/gluex_top/ccdb/ccdb_2.00-test/bin/ccdb
[marki@lorentz gluex_top]$ echo $CCDB_CONNECTION 
mysql://ccdb_user@localhost/ccdb2
[marki@lorentz gluex_top]$ ccdb ls
test
CDC
FCAL
START_COUNTER
PID
FDC
Magnets
Material
TOF
BCAL
Translation
PHOTON_BEAM
TARGET
F1TDC
ANALYSIS
ELECTRON_BEAM
GEOMETRY
TAC
CCAL
DIRC
TOF2
[marki@lorentz gluex_top]$ ccdb -i

+--------------------------+
  CCDB shell v.2.00.00
+--------------------------+
       
Interactive mode
print help to get help
print quit or q to exit
print !<command> to execute shell command
()
Login as   : 'anonymous'
Connect to : 'mysql://ccdb_user@localhost/ccdb2'
Variation  : 'default'
Deflt. run : '0'
/> ls
Traceback (most recent call last):
  File "/scratch/marki/gluex_install_scratch/172/gluex_top/ccdb/ccdb_2.00-test/bin/ccdb", line 5, in <module>
    ccdb.init_ccdb_console()
  File "/scratch/marki/gluex_install_scratch/172/gluex_top/ccdb/ccdb_2.00-test/python/ccdb/__init__.py", line 181, in init_ccdb_console
    result = context.process(sys.argv)
  File "/scratch/marki/gluex_install_scratch/172/gluex_top/ccdb/ccdb_2.00-test/python/ccdb/cmd/cli_manager.py", line 195, in process
    self.interactive_loop()
  File "/scratch/marki/gluex_install_scratch/172/gluex_top/ccdb/ccdb_2.00-test/python/ccdb/cmd/cli_manager.py", line 380, in interactive_loop
    user_input = eval(input(self.context.current_path + "> "))
  File "<string>", line 1, in <module>
NameError: name 'ls' is not defined
```
If I run with a version 1 release of ccdb on the same v2 schema database, both methods work (as expected):

```
[marki@lorentz ~]$ which ccdb
/group/halld/Software/builds/Linux_RHEL7-x86_64-gcc4.8.5/ccdb/ccdb_1.06.07/bin/ccdb
[marki@lorentz ~]$ echo $CCDB_CONNECTION 
mysql://ccdb_user@localhost/ccdb2
[marki@lorentz ~]$ ccdb ls
test
CDC
FCAL
START_COUNTER
PID
FDC
Magnets
Material
TOF
BCAL
Translation
PHOTON_BEAM
TARGET
F1TDC
ANALYSIS
ELECTRON_BEAM
GEOMETRY
TAC
CCAL
DIRC
TOF2
[marki@lorentz ~]$ ccdb -i

+--------------------------+
  CCDB shell v.1.07.00
+--------------------------+
       
Interactive mode
print help to get help
print quit or q to exit
print !<command> to execute shell command

Login as   : 'marki'
Connect to : 'mysql://ccdb_user@localhost/ccdb2'
Variation  : 'default'
Deflt. run : '0'
/> ls
test
CDC
FCAL
START_COUNTER
PID
FDC
Magnets
Material
TOF
BCAL
Translation
PHOTON_BEAM
TARGET
F1TDC
ANALYSIS
ELECTRON_BEAM
GEOMETRY
TAC
CCAL
DIRC
TOF2
/> 
/> q

If I run a ccdb v1 release:
```

**Comment by DraTeots** [comment]
Works in v2.00 now
